create table if not exists person (
    id bigint generated by default as identity primary key,
    name varchar(100) unique not null,
    password varchar not null
);

create table if not exists message (
    id bigint generated by default as identity primary key,
    name varchar(100) references person(name),
    message varchar
);